### ISSUE TITLE
[question] CI tests

### ISSUE THREAD

**Issue by svinota** [jpirko/lnst#101]
Is there CI tests for lnst?

I'm going to change the very base netlink socket class in `pyroute2` [1], but want to be sure it will not break anything in `lnst`. Is there a way to do that w/o asking you to test the changes?

[1] https://github.com/svinota/pyroute2/tree/eventlet — the branch containing the change

**Comment by jtluka** [comment]
Hi Pete, so, atm there's no CI around. However it's possible to check for
regressions within LNST in two ways by your own. Both are present in lnst
git. For both of these you need to have 2 machines, virtual machines
are the easiest to go with.

1. Smoke tests
    git clone https://github.com/jpirko/lnst.git
i
    # add two virtual machines into your test machine pool, check
    https://github.com/jpirko/lnst/wiki/Set-up-Your-Machine-Pool
    https://github.com/jpirko/lnst/wiki/Slave-Description-XML-Format

    ... the following will work

<slavemachine>
    <params>
        <param name="libvirt_domain" value="__my_domain1__"/>
        <param name="hostname" value="__guest1_hostname_or_ipaddr"/>
    </params>
    <interfaces/>
</slavemachine>

    cd lnst
    pushd lnst/recipes/smoke
    ./generate-recipes.py
    popd
    ./lnst-ctl -d run recipes/smoke/tests/
    
2. Regression tests
    git clone https://github.com/jpirko/lnst.git
    cd lnst/regression-tests
    # add two virtual machines into env/pool drictory
    ./run-test.sh -r    

Hope this helps.

-Jan

**Comment by svinota** [comment]
Ok, I'll try.

Thanks!

**Comment by jtluka** [comment]
If it does not work for you feel free to contact us and we'll do the
testing.

**Comment by svinota** [comment]
Regression tests don't work for me at all, I get the same error for all the tests:

```
    Trying recipe file "recipe2.xml" match 1
    ----------------------------------------
2015-02-12 15:47:02       (localhost)        -    INFO: No previous configuration found.
2015-02-12 15:47:02       (localhost)        -    INFO: Checking machine pool availability.
2015-02-12 15:47:02       (localhost)        -    INFO: Processing pool dir '/tmp/tmp.DcvYNVoM5m/pool'
Traceback (most recent call last):
  File "/tmp/tmp.DcvYNVoM5m/lnst-ctl", line 344, in <module>
    sys.exit(main())
  File "/tmp/tmp.DcvYNVoM5m/lnst-ctl", line 322, in main
    reduce_sync, multi_match)
  File "/tmp/tmp.DcvYNVoM5m/lnst-ctl", line 106, in get_recipe_result
    reduce_sync=reduce_sync)
  File "/tmp/tmp.DcvYNVoM5m/lnst/Controller/NetTestController.py", line 72, in __init__
    pool_checks)
  File "/tmp/tmp.DcvYNVoM5m/lnst/Controller/SlavePool.py", line 57, in __init__
    self.add_dir(pool_dir)
  File "/tmp/tmp.DcvYNVoM5m/lnst/Controller/SlavePool.py", line 68, in add_dir
    dentries = os.listdir(dir_path)
OSError: [Errno 2] No such file or directory: '/tmp/tmp.DcvYNVoM5m/pool'
```

Configuration:

```
# cat ~/.lnst/lnst-ctl.conf 
[environment]
mac_pool_range = 52:54:01:00:00:01 52:54:01:FF:FF:FF
rpcport = 9999
machine_pool_dirs += ~/lab
log_dir = ./logs

# ls -l ~/lab/
total 8
-rw-r--r--. 1 root root 355 Feb 12 15:37 machine1.xml
-rw-r--r--. 1 root root 354 Feb 12 15:44 machine2.xml

# cat ~/lab/machine1.xml 
<slavemachine>
    <params>
        <param name="hostname" value="192.168.122.102"/>
        <param name="rpcport" value="9999"/>
    </params>
    <interfaces>
        <eth label="eth0" id="1">
             <params>
                 <param name="hwaddr" value="52:54:00:03:45:a0"/>
             </params>
        </eth>
    </interfaces>
</slavemachine>
```

**Comment by svinota** [comment]
Simple run doesn't work as well:

```
Master:

# lnst-ctl run ping_check.xml
Loading config file '/etc/lnst-ctl.conf'
Loading config file '/root/.lnst/lnst-ctl.conf'
2015-02-12 15:45:30       (localhost)        -    INFO: 
    -------------------------------------------
    Trying recipe file "ping_check.xml" match 1
    -------------------------------------------
2015-02-12 15:45:30       (localhost)        -    INFO: No previous configuration found.
2015-02-12 15:45:30       (localhost)        -    INFO: Checking machine pool availability.
2015-02-12 15:45:30       (localhost)        -    INFO: Processing pool dir '/root/lab'
2015-02-12 15:45:30       (localhost)        -    INFO: machine1 [UP] 
2015-02-12 15:45:30       (localhost)        -    INFO: machine2 [UP] 
2015-02-12 15:45:30       (localhost)        -    INFO: Using pool dir: /root/lab
2015-02-12 15:45:30       (localhost)        -    INFO: Pool match description:
2015-02-12 15:45:30       (localhost)        -    INFO:   host "machine1" uses "machine1"
2015-02-12 15:45:30       (localhost)        -    INFO:     interface "1" matched to "1"
2015-02-12 15:45:30       (localhost)        -    INFO:   host "machine2" uses "machine2"
2015-02-12 15:45:30       (localhost)        -    INFO:     interface "2" matched to "2"
2015-02-12 15:45:30       (localhost)        -    INFO: Connecting to RPC on machine machine1 (192.168.122.102)
2015-02-12 15:45:30       (localhost)        -   ERROR: Exception raised during configuration.
2015-02-12 15:45:30       (localhost)        -   ERROR: [Errno 111] Connection refused
2015-02-12 15:45:30       (localhost)        -    INFO: ======================== SUMMARY ========================
2015-02-12 15:45:30       (localhost)        -    INFO:  ping_check.xml match: 1                            FAIL 
2015-02-12 15:45:30       (localhost)        -    INFO:      Pool match description:  
2015-02-12 15:45:30       (localhost)        -    INFO:      host "machine1" uses "machine1"  
2015-02-12 15:45:30       (localhost)        -    INFO:        interface "1" matched to "1"  
2015-02-12 15:45:30       (localhost)        -    INFO:      host "machine2" uses "machine2"  
2015-02-12 15:45:30       (localhost)        -    INFO:        interface "2" matched to "2"  
2015-02-12 15:45:30       (localhost)        -    INFO:      error message: [Errno 111] Connection refused  
2015-02-12 15:45:30       (localhost)        -    INFO: =========================================================
2015-02-12 15:45:30       (localhost)        -    INFO: Total test time: 0 days, 0 hours, 0 minutes, 0 seconds
```

```
Slave1:

# /usr/local/bin/lnst-slave
Loading config file '/etc/lnst-slave.conf'
2015-02-12 15:45:26       (localhost)        -    INFO: Started
2015-02-12 15:45:26       (localhost)        -    INFO: Waiting for connection.
2015-02-12 15:45:30       (localhost)        -    INFO: Recieved connection from 192.168.122.1
Traceback (most recent call last):
  File "/usr/local/bin/lnst-slave", line 98, in <module>
    main()
  File "/usr/local/bin/lnst-slave", line 95, in main
    nettestslave.run()
  File "/usr/local/lib/python2.7/dist-packages/lnst/Slave/NetTestSlave.py", line 768, in run
    msgs = self._server_handler.get_messages()
  File "/usr/local/lib/python2.7/dist-packages/lnst/Slave/NetTestSlave.py", line 659, in get_messages
    messages = self.check_connections()
  File "/usr/local/lib/python2.7/dist-packages/lnst/Common/ConnectionHandler.py", line 74, in check_connections
    return self._check_connections(self._connections)
  File "/usr/local/lib/python2.7/dist-packages/lnst/Common/ConnectionHandler.py", line 85, in _check_connections
    rl, wl, xl = select.select(connections, [], [])
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netlink/nlsocket.py", line 807, in _forward
    return getattr(self._sock, name)(*args, **kwargs)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
  File "/usr/lib/python2.7/socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
socket.error: [Errno 9] Bad file descriptor
```

**Comment by svinota** [comment]
So, probably, I would rather ask you to perform a quick-test of the pyroute2 branch:

https://github.com/svinota/pyroute2/tree/eventlet

So I would continue the pyroute2 feature integration. After that I will try to set up the lnst environment, but it can take some time.

**Comment by jtluka** [comment]
Checkout out your branch, let's see how lnst works with it. Will post
results in few minutes.

**Comment by jtluka** [comment]
Seems that the eventlet branch works without issues, at least on rhel7 release. Should be safe to go.

**Comment by jtluka** [comment]
My bad, I get following error.

```
Traceback (most recent call last):
  File "./lnst-slave", line 98, in <module>
    main()
  File "./lnst-slave", line 95, in main
    nettestslave.run()
  File "/root/lnst/lnst/Slave/NetTestSlave.py", line 768, in run
    msgs = self._server_handler.get_messages()
  File "/root/lnst/lnst/Slave/NetTestSlave.py", line 659, in get_messages
    messages = self.check_connections()
  File "/root/lnst/lnst/Common/ConnectionHandler.py", line 74, in check_connections
    return self._check_connections(self._connections)
  File "/root/lnst/lnst/Common/ConnectionHandler.py", line 85, in _check_connections
    rl, wl, xl = select.select(connections, [], [])
  File "/usr/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.py", line 807, in _forward
    return getattr(self._sock, name)(*args, **kwargs)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
  File "/usr/lib64/python2.7/socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
socket.error: [Errno 9] Bad file descriptor
```

**Comment by svinota** [comment]
So it doesn't work, obviously and will not be merged unless we fix it.

Thanks for verifying. I can reproduce it, so will fix it next week.

Thanks again!

**Comment by svinota** [comment]
Decided to keep old (compatible) architecture as the default, at the same time providing the ability to change it. So the issue is not applicable any more.

Also, closing CI request, since regression tests are there.

Thanks!

**Comment by anguslees** [comment]
Fwiw, the above stacktrace indicates that a method was called on a closed socket.  (Specifically, `__getattr__` was called on `_closedsocket`, which `_socketobject` only uses after `_socketobject.close()` has been called.)

I don't know anything about LNST (and haven't looked further back in the stacktrace), but it seems odd that the patch under test above changed the time when `close()` was called...
