### ISSUE TITLE
interface mapping not cleaned up on exception

### ISSUE THREAD

**Issue by jtluka** [jpirko/lnst#106]
I've hit this issue on buggy recipe, where bonding mode was specified as 'round-robin' this caused exception:
```
[igyn@dhcp-2-157 gre]$ sudo ~/tmp/lnst/lnst-ctl -d run gre-bonding.xml 
Loading config file '/home/igyn/tmp/lnst/lnst-ctl.conf'
Loading config file '/root/.lnst/lnst-ctl.conf'
2015-02-26 15:03:18       (localhost)        -    INFO: 
    --------------------------------------------
    Trying recipe file "gre-bonding.xml" match 1
    --------------------------------------------
2015-02-26 15:03:18       (localhost)        -    INFO: No previous configuration found.
2015-02-26 15:03:18       (localhost)        -    INFO: Checking machine pool availability.
2015-02-26 15:03:18       (localhost)        -    INFO: Processing pool dir '/home/igyn/.lnst/pool2'
2015-02-26 15:03:18       (localhost)        -   DEBUG: Querying machine 'fedora20': fedora20:9999
2015-02-26 15:03:18       (localhost)        -   DEBUG: Querying machine 'fedora20-2': fedora20-2:9999
2015-02-26 15:03:18       (localhost)        -    INFO: fedora20   [UP]    libvirt_domain: fedora20
2015-02-26 15:03:18       (localhost)        -    INFO: fedora20-2 [UP]    libvirt_domain: fedora20-2
2015-02-26 15:03:18       (localhost)        -    INFO: Using pool dir: /home/igyn/.lnst/pool2
2015-02-26 15:03:18       (localhost)        -   DEBUG: Executing: "cd "/home/igyn/tmp/lnst/test_tools" && tar cf "/tmp/tmpl5zy8k" "multicast""
2015-02-26 15:03:18       (localhost)        -   DEBUG: Executing: "cd "/home/igyn/tmp/lnst/test_tools" && tar cf "/tmp/tmpfc7eCC" "tcp_corrupt""
2015-02-26 15:03:18       (localhost)        -   DEBUG: Executing: "cd "/home/igyn/tmp/lnst/test_tools" && tar cf "/tmp/tmpwTzkUP" "tcp_conn""
2015-02-26 15:03:18       (localhost)        -    INFO: Match failed for normal machines, falling back to matching virtual machines.
2015-02-26 15:03:18       (localhost)        -    INFO: Using pool dir: /home/igyn/.lnst/pool2
2015-02-26 15:03:18       (localhost)        -    INFO: Pool match description:
2015-02-26 15:03:18       (localhost)        -    INFO:   Setup is using virtual machines.
2015-02-26 15:03:18       (localhost)        -    INFO:   host "testmachine1" uses "fedora20"
2015-02-26 15:03:18       (localhost)        -    INFO:   host "testmachine2" uses "fedora20-2"
2015-02-26 15:03:18       (localhost)        -    INFO: Connecting to RPC on machine testmachine1 (fedora20)
2015-02-26 15:03:19    (testmachine1)        -    INFO: Performing machine cleanup.
2015-02-26 15:03:19    (testmachine1)        -   DEBUG: Cleaning up leftover processes.
2015-02-26 15:03:19    (testmachine1)        -    INFO: Restoring system configuration
2015-02-26 15:03:19    (testmachine1)        -    INFO: Recieved a controller connection.
2015-02-26 15:03:20    (testmachine1)        - WARNING: =============================================
2015-02-26 15:03:20    (testmachine1)        - WARNING: NetworkManager is running on a slave machine!
2015-02-26 15:03:20    (testmachine1)        - WARNING: Support of NM is still experimental!
2015-02-26 15:03:20    (testmachine1)        - WARNING: =============================================
2015-02-26 15:03:20       (localhost)        -   DEBUG: libvirt network 'lnst_net0' created
2015-02-26 15:03:20       (localhost)        -    INFO: Creating interface phy2 (52:54:01:00:00:01) on machine testmachine1
2015-02-26 15:03:20       (localhost)        -   DEBUG: libvirt device with hwaddr '52:54:01:00:00:01'driver 'virtio' attached
2015-02-26 15:03:23    (testmachine1)        -   DEBUG: Executing: "ip link set eth1 down"
2015-02-26 15:03:22       (localhost)        -    INFO: Creating interface phy1 (52:54:01:00:00:02) on machine testmachine1
2015-02-26 15:03:22       (localhost)        -   DEBUG: libvirt device with hwaddr '52:54:01:00:00:02'driver 'virtio' attached
2015-02-26 15:03:26    (testmachine1)        -   DEBUG: Executing: "ip link set eth2 down"
2015-02-26 15:03:26    (testmachine1)        -   DEBUG: Test cache index commited
2015-02-26 15:03:26    (testmachine1)        -   DEBUG: Test cache index commited
2015-02-26 15:03:26    (testmachine1)        -   DEBUG: Test cache index commited
2015-02-26 15:03:26    (testmachine1)        -   DEBUG: Test cache index commited
2015-02-26 15:03:26    (testmachine1)        -   DEBUG: Test cache index commited
2015-02-26 15:03:26    (testmachine1)        -   DEBUG: Test cache index commited
2015-02-26 15:03:26    (testmachine1)        -   DEBUG: Test cache index commited
2015-02-26 15:03:26    (testmachine1)        -   DEBUG: Test cache index commited
2015-02-26 15:03:26    (testmachine1)        -   DEBUG: Test cache index commited
2015-02-26 15:03:26    (testmachine1)        -   DEBUG: Test cache index commited
2015-02-26 15:03:26    (testmachine1)        -   DEBUG: Test cache index commited
2015-02-26 15:03:26    (testmachine1)        -   DEBUG: Test cache index commited
2015-02-26 15:03:26    (testmachine1)        -   DEBUG: Test cache index commited
2015-02-26 15:03:26    (testmachine1)        -   DEBUG: Test cache index commited
2015-02-26 15:03:24       (localhost)        -    INFO: Connecting to RPC on machine testmachine2 (fedora20-2)
2015-02-26 15:03:26    (testmachine2)        -    INFO: Performing machine cleanup.
2015-02-26 15:03:26    (testmachine2)        -   DEBUG: Cleaning up leftover processes.
2015-02-26 15:03:26    (testmachine2)        -    INFO: Restoring system configuration
2015-02-26 15:03:26    (testmachine2)        -    INFO: Recieved a controller connection.
2015-02-26 15:03:27    (testmachine2)        - WARNING: =============================================
2015-02-26 15:03:27    (testmachine2)        - WARNING: NetworkManager is running on a slave machine!
2015-02-26 15:03:27    (testmachine2)        - WARNING: Support of NM is still experimental!
2015-02-26 15:03:27    (testmachine2)        - WARNING: =============================================
2015-02-26 15:03:25       (localhost)        -    INFO: Creating interface phy2 (52:54:01:00:00:03) on machine testmachine2
2015-02-26 15:03:25       (localhost)        -   DEBUG: libvirt device with hwaddr '52:54:01:00:00:03'driver 'virtio' attached
2015-02-26 15:03:29    (testmachine2)        -   DEBUG: Executing: "ip link set eth1 down"
2015-02-26 15:03:27       (localhost)        -    INFO: Creating interface phy1 (52:54:01:00:00:04) on machine testmachine2
2015-02-26 15:03:27       (localhost)        -   DEBUG: libvirt device with hwaddr '52:54:01:00:00:04'driver 'virtio' attached
2015-02-26 15:03:31    (testmachine2)        -   DEBUG: Executing: "ip link set eth2 down"
2015-02-26 15:03:31    (testmachine2)        -   DEBUG: Test cache index commited
2015-02-26 15:03:31    (testmachine2)        -   DEBUG: Test cache index commited
2015-02-26 15:03:31    (testmachine2)        -   DEBUG: Test cache index commited
2015-02-26 15:03:31    (testmachine2)        -   DEBUG: Test cache index commited
2015-02-26 15:03:31    (testmachine2)        -   DEBUG: Test cache index commited
2015-02-26 15:03:31    (testmachine2)        -   DEBUG: Test cache index commited
2015-02-26 15:03:31    (testmachine2)        -   DEBUG: Test cache index commited
2015-02-26 15:03:31    (testmachine2)        -   DEBUG: Test cache index commited
2015-02-26 15:03:31    (testmachine2)        -   DEBUG: Test cache index commited
2015-02-26 15:03:31    (testmachine2)        -   DEBUG: Test cache index commited
2015-02-26 15:03:31    (testmachine2)        -   DEBUG: Test cache index commited
2015-02-26 15:03:31    (testmachine2)        -   DEBUG: Test cache index commited
2015-02-26 15:03:31    (testmachine2)        -   DEBUG: Test cache index commited
2015-02-26 15:03:31    (testmachine2)        -   DEBUG: Test cache index commited
2015-02-26 15:03:30       (localhost)        -    INFO: Configuring interface phy2 on machine testmachine1
2015-02-26 15:03:31    (testmachine1)        -   DEBUG: Executing: "ethtool -A eth1 rx off tx off"
2015-02-26 15:03:30       (localhost)        -    INFO: Configuring interface phy1 on machine testmachine1
2015-02-26 15:03:31    (testmachine1)        -   DEBUG: Executing: "ethtool -A eth2 rx off tx off"
2015-02-26 15:03:30       (localhost)        -    INFO: Configuring interface nic1 on machine testmachine1
2015-02-26 15:03:32    (testmachine1)        -   DEBUG: 
    Traceback (most recent call last):
      File "/root/lnst/lnst/Slave/NetTestSlave.py", line 794, in _process_msg
        result = method(*msg["args"])
      File "/root/lnst/lnst/Slave/NetTestSlave.py", line 176, in create_soft_interface
        dev.configure()
      File "/root/lnst/lnst/Slave/InterfaceManager.py", line 446, in configure
        self._conf.configure()
      File "/root/lnst/lnst/Slave/NmConfigDevice.py", line 487, in configure
        self._add_bond()
      File "/root/lnst/lnst/Slave/NmConfigDevice.py", line 460, in _add_bond
        self._nm_add_connection()
      File "/root/lnst/lnst/Slave/NmConfigDevice.py", line 227, in _nm_add_connection
        self._con_obj_path = settings_if.AddConnection(self._connection)
      File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 70, in __call__
<lnstrecipe>
        return self._proxy_method(*args, **keywords)
      File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
        **keywords)
      File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
        message, timeout)
    DBusException: org.freedesktop.DBus.GLib.UnmappedError.NmSettingBondErrorQuark.Code3: bond.options: 'round-robin' is not a valid value for 'mode'
    
2015-02-26 15:03:30       (localhost)        -   ERROR: Exception raised during configuration.
2015-02-26 15:03:32    (testmachine1)        -    INFO: Killing all forked processes.
2015-02-26 15:03:32    (testmachine1)        -   DEBUG: Cleaning up leftover processes.
2015-02-26 15:03:30       (localhost)        -   DEBUG: libvirt device with hwaddr '52:54:01:00:00:02' detached
2015-02-26 15:03:30       (localhost)        -   DEBUG: libvirt device with hwaddr '52:54:01:00:00:01' detached
2015-02-26 15:03:32    (testmachine1)        -    INFO: Restoring system configuration
2015-02-26 15:03:32    (testmachine2)        -    INFO: Killing all forked processes.
2015-02-26 15:03:32    (testmachine2)        -   DEBUG: Cleaning up leftover processes.
2015-02-26 15:03:30       (localhost)        -   DEBUG: libvirt device with hwaddr '52:54:01:00:00:04' detached
2015-02-26 15:03:30       (localhost)        -   DEBUG: libvirt device with hwaddr '52:54:01:00:00:03' detached
2015-02-26 15:03:32    (testmachine2)        -    INFO: Restoring system configuration
2015-02-26 15:03:32       (localhost)        -   DEBUG: libvirt network 'lnst_net0' destroyed
2015-02-26 15:03:32       (localhost)        -   DEBUG: 
    Traceback (most recent call last):
      File "/home/igyn/tmp/lnst/lnst-ctl", line 124, in get_recipe_result
        res = exec_action(action, nettestctl)
      File "/home/igyn/tmp/lnst/lnst-ctl", line 81, in exec_action
        return nettestctl.run_recipe()
      File "/home/igyn/tmp/lnst/lnst/Controller/NetTestController.py", line 619, in run_recipe
        self._prepare_network()
      File "/home/igyn/tmp/lnst/lnst/Controller/NetTestController.py", line 206, in _prepare_network
        iface.configure()
      File "/home/igyn/tmp/lnst/lnst/Controller/Machine.py", line 905, in configure
        self._id, self._get_config())
      File "/home/igyn/tmp/lnst/lnst/Controller/Machine.py", line 154, in _rpc_call
        result = self._msg_dispatcher.wait_for_result(self._id)
      File "/home/igyn/tmp/lnst/lnst/Controller/NetTestController.py", line 867, in wait_for_result
        self._process_message(msg)
      File "/home/igyn/tmp/lnst/lnst/Controller/NetTestController.py", line 890, in _process_message
        raise CommandException(msg)
    CommandException: CommandException: Slave testmachine1: org.freedesktop.DBus.GLib.UnmappedError.NmSettingBondErrorQuark.Code3: bond.options: 'round-robin' is not a valid value for 'mode'
    
2015-02-26 15:03:32       (localhost)        -   ERROR: CommandException: Slave testmachine1: org.freedesktop.DBus.GLib.UnmappedError.NmSettingBondErrorQuark.Code3: bond.options: 'round-robin' is not a valid value for 'mode'
2015-02-26 15:03:32       (localhost)        -    INFO: ============================================================================================= SUMMARY =============================================================================================
2015-02-26 15:03:32       (localhost)        -    INFO:  gre-bonding.xml match: 1                                                                                                                                                                     FAIL 
2015-02-26 15:03:32       (localhost)        -    INFO:      Pool match description:  
2015-02-26 15:03:32       (localhost)        -    INFO:      Setup is using virtual machines.  
2015-02-26 15:03:32       (localhost)        -    INFO:      host "testmachine1" uses "fedora20"  
2015-02-26 15:03:32       (localhost)        -    INFO:      host "testmachine2" uses "fedora20-2"  
2015-02-26 15:03:32       (localhost)        -    INFO:      error message: CommandException: Slave testmachine1: org.freedesktop.DBus.GLib.UnmappedError.NmSettingBondErrorQuark.Code3: bond.options: 'round-robin' is not a valid value for 'mode'  
2015-02-26 15:03:32       (localhost)        -    INFO: ===================================================================================================================================================================================================
2015-02-26 15:03:32       (localhost)        -    INFO: Total test time: 0 days, 0 hours, 0 minutes, 13 seconds
```

So I modified the recipe and wanted to run it again but got this failure,

```
[igyn@dhcp-2-157 gre]$ sudo ~/tmp/lnst/lnst-ctl -d run gre-bonding.xml 
Loading config file '/home/igyn/tmp/lnst/lnst-ctl.conf'
Loading config file '/root/.lnst/lnst-ctl.conf'
2015-02-26 15:04:00       (localhost)        -    INFO: 
    --------------------------------------------
    Trying recipe file "gre-bonding.xml" match 1
    --------------------------------------------
2015-02-26 15:04:00       (localhost)        -    INFO: No previous configuration found.
2015-02-26 15:04:00       (localhost)        -    INFO: Checking machine pool availability.
2015-02-26 15:04:00       (localhost)        -    INFO: Processing pool dir '/home/igyn/.lnst/pool2'
2015-02-26 15:04:00       (localhost)        -   DEBUG: Querying machine 'fedora20': fedora20:9999
2015-02-26 15:04:00       (localhost)        -   DEBUG: Querying machine 'fedora20-2': fedora20-2:9999
2015-02-26 15:04:00       (localhost)        -    INFO: fedora20   [UP]    libvirt_domain: fedora20
2015-02-26 15:04:00       (localhost)        -    INFO: fedora20-2 [UP]    libvirt_domain: fedora20-2
2015-02-26 15:04:00       (localhost)        -    INFO: Using pool dir: /home/igyn/.lnst/pool2
2015-02-26 15:04:00       (localhost)        -   DEBUG: Executing: "cd "/home/igyn/tmp/lnst/test_tools" && tar cf "/tmp/tmpK9i_VB" "multicast""
2015-02-26 15:04:00       (localhost)        -   DEBUG: Executing: "cd "/home/igyn/tmp/lnst/test_tools" && tar cf "/tmp/tmp5zN54A" "tcp_corrupt""
2015-02-26 15:04:00       (localhost)        -   DEBUG: Executing: "cd "/home/igyn/tmp/lnst/test_tools" && tar cf "/tmp/tmpdvcR0L" "tcp_conn""
2015-02-26 15:04:00       (localhost)        -    INFO: Match failed for normal machines, falling back to matching virtual machines.
2015-02-26 15:04:00       (localhost)        -    INFO: Using pool dir: /home/igyn/.lnst/pool2
2015-02-26 15:04:00       (localhost)        -    INFO: Pool match description:
2015-02-26 15:04:00       (localhost)        -    INFO:   Setup is using virtual machines.
2015-02-26 15:04:00       (localhost)        -    INFO:   host "testmachine1" uses "fedora20"
2015-02-26 15:04:00       (localhost)        -    INFO:   host "testmachine2" uses "fedora20-2"
2015-02-26 15:04:00       (localhost)        -    INFO: Connecting to RPC on machine testmachine1 (fedora20)
2015-02-26 15:04:02    (testmachine1)        -    INFO: Performing machine cleanup.
2015-02-26 15:04:02    (testmachine1)        -   DEBUG: Cleaning up leftover processes.
2015-02-26 15:04:02    (testmachine1)        -   DEBUG: 
    Traceback (most recent call last):
      File "/root/lnst/lnst/Slave/NetTestSlave.py", line 794, in _process_msg
        result = method(*msg["args"])
      File "/root/lnst/lnst/Slave/NetTestSlave.py", line 72, in hello
        self.machine_cleanup()
      File "/root/lnst/lnst/Slave/NetTestSlave.py", line 379, in machine_cleanup
        dev.clear_configuration()
      File "/root/lnst/lnst/Slave/InterfaceManager.py", line 393, in clear_configuration
        self.down()
      File "/root/lnst/lnst/Slave/InterfaceManager.py", line 473, in down
        self._conf.down()
      File "/root/lnst/lnst/Slave/NmConfigDevice.py", line 408, in down
        slave_dev = self._if_manager.get_mapped_device(slave_id)
      File "/root/lnst/lnst/Slave/InterfaceManager.py", line 135, in get_mapped_device
        raise IfMgrError("No device with id %s mapped." % if_id)
    IfMgrError: No device with id phy2 mapped.
    
2015-02-26 15:04:00       (localhost)        -   ERROR: Exception raised during configuration.
2015-02-26 15:04:00       (localhost)        -   DEBUG: 
    Traceback (most recent call last):
      File "/home/igyn/tmp/lnst/lnst-ctl", line 124, in get_recipe_result
        res = exec_action(action, nettestctl)
      File "/home/igyn/tmp/lnst/lnst-ctl", line 81, in exec_action
        return nettestctl.run_recipe()
      File "/home/igyn/tmp/lnst/lnst/Controller/NetTestController.py", line 619, in run_recipe
        self._prepare_network()
      File "/home/igyn/tmp/lnst/lnst/Controller/NetTestController.py", line 186, in _prepare_network
        self._prepare_machine(m_id, resource_sync)
      File "/home/igyn/tmp/lnst/lnst/Controller/NetTestController.py", line 248, in _prepare_machine
        machine.configure(recipe_name)
      File "/home/igyn/tmp/lnst/lnst/Controller/Machine.py", line 183, in configure
        hello = self._rpc_call("hello", recipe_name)
      File "/home/igyn/tmp/lnst/lnst/Controller/Machine.py", line 154, in _rpc_call
        result = self._msg_dispatcher.wait_for_result(self._id)
      File "/home/igyn/tmp/lnst/lnst/Controller/NetTestController.py", line 867, in wait_for_result
        self._process_message(msg)
      File "/home/igyn/tmp/lnst/lnst/Controller/NetTestController.py", line 890, in _process_message
        raise CommandException(msg)
    CommandException: CommandException: Slave testmachine1: No device with id phy2 mapped.
    
2015-02-26 15:04:00       (localhost)        -   ERROR: CommandException: Slave testmachine1: No device with id phy2 mapped.
2015-02-26 15:04:00       (localhost)        -    INFO: =========================================== SUMMARY ===========================================
2015-02-26 15:04:00       (localhost)        -    INFO:  gre-bonding.xml match: 1                                                                 FAIL 
2015-02-26 15:04:00       (localhost)        -    INFO:      Pool match description:  
2015-02-26 15:04:00       (localhost)        -    INFO:      Setup is using virtual machines.  
2015-02-26 15:04:00       (localhost)        -    INFO:      host "testmachine1" uses "fedora20"  
2015-02-26 15:04:00       (localhost)        -    INFO:      host "testmachine2" uses "fedora20-2"  
2015-02-26 15:04:00       (localhost)        -    INFO:      error message: CommandException: Slave testmachine1: No device with id phy2 mapped.  
2015-02-26 15:04:00       (localhost)        -    INFO: ===============================================================================================
2015-02-26 15:04:00       (localhost)        -    INFO: Total test time: 0 days, 0 hours, 0 minutes, 0 seconds
```

**Comment by jtluka** [comment]
Attaching the recipe (not including the python task since it's irrelevant, 'config_only' should work).

```
<lnstrecipe>
    <network>
        <host id="testmachine1">
            <params/>
            <interfaces>
                <eth id="phy1" label="testnet"/>
                <eth id="phy2" label="testnet"/>
                <bond id="nic1">
                    <options>
                        <option name="mode" value="balance-rr"/>
                    </options>
                    <slaves>
                        <slave id="phy1"/>
                        <slave id="phy2"/>
                    </slaves>
                    <addresses>
                        <address>192.168.100.2/24</address>
                        <address>fe01::1/64</address>
                    </addresses>
                </bond>
            </interfaces>
        </host>
        <host id="testmachine2">
            <params/>
            <interfaces>
                <eth id="phy1" label="testnet"/>
                <eth id="phy2" label="testnet"/>
                <bond id="nic1">
                    <options>
                        <option name="mode" value="balance-rr"/>
                    </options>
                    <slaves>
                        <slave id="phy1"/>
                        <slave id="phy2"/>
                    </slaves>
                    <addresses>
                        <address>192.168.100.3/24</address>
                        <address>fe01::2/64</address>
                    </addresses>
                </bond>
            </interfaces>
        </host>
    </network>

    <task python="gre.py"/>
</lnstrecipe>
```
