### ISSUE TITLE
sometimes netperf client gives traceback

### ISSUE THREAD

**Issue by jtluka** [jpirko/lnst#120]
Looks like netperf client reports result but also is about to be killed, but meanwhile it's process id is removed. Probably race condition.

```
2015-06-19 13:53:02       (localhost)        -    INFO: Executing command: [type(test), module(Netperf), host(testmachine1), bg_id(11)]
2015-06-19 13:53:02       (localhost)        -   DEBUG: Setting default timeout (60s).
2015-06-19 13:53:02    (testmachine1)        -   DEBUG: Running in background with bg_id "11" pid "18119"
2015-06-19 13:53:02    (testmachine1)        -   DEBUG: compiled command: netserver -D -L 192.168.20.1
2015-06-19 13:53:02    (testmachine1)        -   DEBUG: running as server...
2015-06-19 13:53:02       (localhost)        -    INFO: Result: PASS
2015-06-19 13:53:02       (localhost)        -    INFO: Status message from slave: "Running in background."
2015-06-19 13:53:02       (localhost)        -    INFO: Executing command: [type(ctl_wait), seconds(2)]
2015-06-19 13:53:04       (localhost)        -    INFO: Executing command: [type(test), module(Netperf), host(testmachine2), timeout(70)]
2015-06-19 13:53:04       (localhost)        -   DEBUG: Setting timeout to "70"
2015-06-19 13:53:04    (testmachine2)        -   DEBUG: Running command with pid "1438"
2015-06-19 13:53:04    (testmachine2)        -   DEBUG: compiled command: netperf -H 192.168.20.1 -f k -l 60 -t TCP_STREAM -L 192.168.20.2
2015-06-19 13:53:04    (testmachine2)        -   DEBUG: running as client...
2015-06-19 13:54:04    (testmachine2)        -   DEBUG: 
    data:
    MIGRATED TCP STREAM TEST from 192.168.20.2 () port 0 AF_INET to 192.168.20.1 () port 0 AF_INET
    Recv   Send    Send                          
    Socket Socket  Message  Elapsed              
    Size   Size    Size     Time     Throughput  
    bytes  bytes   bytes    secs.    10^3bits/sec  
    
     87380  16384  16384    60.00    9497155.61
2015-06-19 13:54:14    (testmachine2)        -   DEBUG: 
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/lnst/Slave/NetTestSlave.py", line 813, in _process_msg
        result = method(*msg["args"])
      File "/usr/lib/python2.6/site-packages/lnst/Slave/NetTestSlave.py", line 385, in kill_command
        cmd = self._command_context.get_cmd(id)
      File "/usr/lib/python2.6/site-packages/lnst/Common/NetTestCommand.py", line 232, in get_cmd
        return self._dict[id]
    KeyError: None
    
2015-06-19 13:54:17       (localhost)        -   DEBUG: CommandException: Slave testmachine2: None
```

**Comment by jtluka** [comment]
Since we have not seen this recently it is probably fixed by the commit above. Closing
