### ISSUE TITLE
traceback when down-ing unused interface

### ISSUE THREAD

**Issue by olichtne** [jpirko/lnst#122]
```
2015-06-19 09:46:23    (testmachine1)        -   DEBUG: 
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/lnst/Slave/NetTestSlave.py", line 813, in _process_msg
        result = method(*msg["args"])
      File "/usr/lib/python2.6/site-packages/lnst/Slave/NetTestSlave.py", line 180, in set_unmapped_device_down
        dev.down()
    AttributeError: 'NoneType' object has no attribute 'down'
    
2015-06-19 09:46:23       (localhost)        -   ERROR: Exception raised during configuration.
2015-06-19 09:46:23       (localhost)        -   DEBUG: 
    Traceback (most recent call last):
      File "/usr/bin/lnst-ctl", line 124, in get_recipe_result
        res = exec_action(action, nettestctl)
      File "/usr/bin/lnst-ctl", line 81, in exec_action
        return nettestctl.run_recipe()
      File "/usr/lib/python2.6/site-packages/lnst/Controller/NetTestController.py", line 623, in run_recipe
        self._prepare_network()
      File "/usr/lib/python2.6/site-packages/lnst/Controller/NetTestController.py", line 186, in _prepare_network
        self._prepare_machine(m_id, resource_sync)
      File "/usr/lib/python2.6/site-packages/lnst/Controller/NetTestController.py", line 249, in _prepare_machine
        machine.configure(recipe_name)
      File "/usr/lib/python2.6/site-packages/lnst/Controller/Machine.py", line 205, in configure
        iface.initialize()
      File "/usr/lib/python2.6/site-packages/lnst/Controller/Machine.py", line 1022, in initialize
        self._machine._rpc_call('set_unmapped_device_down', self._hwaddr)
      File "/usr/lib/python2.6/site-packages/lnst/Controller/Machine.py", line 167, in _rpc_call
        result = self._msg_dispatcher.wait_for_result(self._id)
      File "/usr/lib/python2.6/site-packages/lnst/Controller/NetTestController.py", line 874, in wait_for_result
        self._process_message(msg)
      File "/usr/lib/python2.6/site-packages/lnst/Controller/NetTestController.py", line 897, in _process_message
        raise CommandException(msg)
    CommandException: CommandException: Slave testmachine1: 'NoneType' object has no attribute 'down'

```

**Comment by jtluka** [comment]
Seen with following setup:
PYROUTE_UPSTREAM yes
PYROUTE_HASH 62791d76b024f7c0dc50e556430084902ac1e463
DEFAULT_PYROUTE_VERSION 0.3.6
TEST_SOURCE UPSTREAM
LNST_VERSION HEAD
/mnt/testarea /mnt/tests/kernel/distribution/lnst/install
Cloning LNST from https://github.com/jpirko/lnst.git
Initialized empty Git repository in /mnt/testarea/lnst/.git/
/mnt/testarea/lnst /mnt/testarea /mnt/tests/kernel/distribution/lnst/install
Resetting to revision HEAD
HEAD is now at 831b186 Netperf: major refactorization

**Comment by jtluka** [comment]
So, I reproduced this issue on the same system. Looks like there was inconsistency between slavemachine xml and devices available on the system. The xml file had two devices that were not physically available that resulted in traceback. We should handle these situations as they might be quite common, e.g. when test machine's NICs are removed. Either we should handle it in this function or what would be more clever, to remove them from the pool during matching, with some kind of probe.

**Comment by jtluka** [comment]
Note: the issue was with buggy kernel, that did not make the device available for use despite it was physically attached to the system. Therefore we got no crash with rhel6.7 and crash with previous 6.6

**Comment by olichtne** [comment]
Great, properly handling the traceback won't be a problem then... I can fix this once I'm back in the office.
