### ISSUE TITLE
getting driver info fails for some device types e.g. ip6_tunnel

### ISSUE THREAD

**Issue by jtluka** [jpirko/lnst#132]
```
[root@localhost lnst]# ./lnst-slave -d
Loading config file '/root/lnst/lnst-slave.conf'
2015-07-09 18:39:11       (localhost)        -    INFO: Started
2015-07-09 18:39:11       (localhost)        -   DEBUG: Executing: "ethtool -i eth0"
2015-07-09 18:39:11       (localhost)        -   DEBUG: Executing: "ethtool -i ip6tnl0"
Traceback (most recent call last):
  File "./lnst-slave", line 98, in <module>
    main()
  File "./lnst-slave", line 90, in main
    nettestslave = NetTestSlave(log_ctl)
  File "/root/lnst/lnst/Slave/NetTestSlave.py", line 759, in __init__
    self._if_manager = InterfaceManager(self._server_handler)
  File "/root/lnst/lnst/Slave/InterfaceManager.py", line 41, in __init__
    self.rescan_devices()
  File "/root/lnst/lnst/Slave/InterfaceManager.py", line 87, in rescan_devices
    device.init_netlink(dev['netlink_msg'])
  File "/root/lnst/lnst/Slave/InterfaceManager.py", line 292, in init_netlink
    self._driver = self._ethtool_get_driver()
  File "/root/lnst/lnst/Slave/InterfaceManager.py", line 501, in _ethtool_get_driver
    return match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
[root@localhost lnst]# ip l
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 52:54:00:42:c4:66 brd ff:ff:ff:ff:ff:ff
5: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN mode DEFAULT group default 
    link/tunnel6 :: brd ::
```

**Comment by jtluka** [comment]
I think that we're interested only in devices of ifi_type == 1. We already exclude loopback type from querying driver info.

ip6_tunnel is ifi_type == 769

```python
    def _ethtool_get_driver(self):
        if self._ifi_type == 772:  #loopback ifi type
            return 'loopback'
```

**Comment by olichtne** [comment]
I have a fix for this in my repository - in case the match fails return an empty string instead. I'll post it tomorrow. Further modification for specific device types can be added later as well.

**Comment by jtluka** [comment]
How about completely ignore non-ethernet devices? The driver information is only relevant for them, e.g. displaying in logs. Why do we want to keep this for other devices?

**Comment by jtluka** [comment]
Already applied. Closing. Commit 6084ed7121c4c0cdbbe02a2263133761aa24566d
