### ISSUE TITLE
unhandled Exception: No such namespace!

### ISSUE THREAD

**Issue by jtluka** [jpirko/lnst#135]
Got traceback with buggy python task where I used m.run("cat a", netns="xyz") but the namespace has not been configured in xml.

```
Traceback (most recent call last):
  File "./lnst-slave", line 98, in <module>
    main()
  File "./lnst-slave", line 95, in main
    nettestslave.run()
  File "/root/lnst/lnst/Slave/NetTestSlave.py", line 793, in run
    self._process_msg(msg[1])
  File "/root/lnst/lnst/Slave/NetTestSlave.py", line 872, in _process_msg
    self._server_handler.send_data_to_netns(netns, msg["data"])
  File "/root/lnst/lnst/Slave/NetTestSlave.py", line 721, in send_data_to_netns
    raise Exception("No such namespace!")
Exception: No such namespace!
```

**Comment by jtluka** [comment]
https://lists.fedorahosted.org/pipermail/lnst-developers/2015-July/002993.html
