### ISSUE TITLE
print the path of python task that does not exist

### ISSUE THREAD

**Issue by jtluka** [jpirko/lnst#160]
This is the traceback I get when I have incorrect path to python task in recipe xml. The controller should print the path instead of object instance.

```
    Traceback (most recent call last):
      File "/home/igyn/tmp/lnst/lnst-ctl", line 129, in get_recipe_result
        res = exec_action(action, nettestctl)
      File "/home/igyn/tmp/lnst/lnst-ctl", line 84, in exec_action
        return nettestctl.run_recipe()
      File "/home/igyn/tmp/lnst/lnst/Controller/NetTestController.py", line 638, in run_recipe
        self._prepare_tasks()
      File "/home/igyn/tmp/lnst/lnst/Controller/NetTestController.py", line 378, in _prepare_tasks
        raise RecipeError(msg, task_data)
    RecipeError: Parser error: /home/igyn/testing/dualstack-tests/ipv6-test.xml:46: Task file '<lnst.Common.Path.Path instance at 0x7f4ece7d3368>' not found.
    
2015-12-16 14:01:37       (localhost)        -   ERROR: Parser error: /home/igyn/testing/dualstack-tests/ipv6-test.xml:46: Task file '<lnst.Common.Path.Path instance at 0x7f4ece7d3368>' not found.
```

**Comment by olichtne** [comment]
fixed in 04b1f5b49670630d7f5e5c115c8179e54f345e72 closing issue
