### ISSUE TITLE
strip authentication type read from pool

### ISSUE THREAD

**Issue by jtluka** [jpirko/lnst#171]
With slavemachine files created with pool wizard with none authentication I get following error:

```
2016-05-05 09:56:58       (localhost)        -   ERROR: Exception raised during configuration.
2016-05-05 09:56:58       (localhost)        -   DEBUG: 
    Traceback (most recent call last):
      File "/root/lnst-ovs/lnst-ctl", line 131, in get_recipe_result
        res = exec_action(action, nettestctl)
      File "/root/lnst-ovs/lnst-ctl", line 86, in exec_action
        return nettestctl.run_recipe()
      File "/root/lnst-ovs/lnst/Controller/NetTestController.py", line 647, in run_recipe
        self._prepare_network()
      File "/root/lnst-ovs/lnst/Controller/NetTestController.py", line 198, in _prepare_network
        self._prepare_machine(m_id, resource_sync)
      File "/root/lnst-ovs/lnst/Controller/NetTestController.py", line 263, in _prepare_machine
        machine.init_connection(recipe_name)
      File "/root/lnst-ovs/lnst/Controller/Machine.py", line 240, in init_connection
        connection.handshake(self._security)
      File "/root/lnst-ovs/lnst/Controller/CtlSecSocket.py", line 115, in handshake
        raise SecSocketException("Unknown authentication method.")
    SecSocketException: Unknown authentication method.
```

The slavemachine xml content:
```xml
<?xml version="1.0" ?>
<slavemachine>
    <params>
        <param name="hostname" value="rhel72-g1"/>
        <param name="libvirt_domain" value="rhel72-g1"/>
        <param name="rpc_port" value="9999"/>
    </params>
    <interfaces/>
    <security>
        <auth_type>
            none
        </auth_type>
    </security>
</slavemachine>
```
The problem seems to be that slavemachine parser does not strip the auth_type data since changing to
```xml
        <auth_type>none</auth_type>
```
solves the problem.

**Comment by jiriprochazka** [comment]
We could just strip whitespaces from parsed auth_type string in SlaveMachineParser or implement this strip functionality for all the tags used in SlaveMachineParser.

I think stripping the auth_type will be sufficient, in SlaveMachineParser.py at line 79 we can just add .strip() to auth_passwd_tag.text and it will work for both cases.

**Comment by olichtne** [comment]
Strip just the auth_type.... we really shouldn't strip everything globally.

Whitespaces in XML files are significant by definition, we can only do pretty printing/ human readable formatting if we ignore this in some places. This can lead to a lot of problems as you can see with this issue... but the default action should still be to not strip anything and do it just where we actually need it.

**Comment by jiriprochazka** [comment]
Fixed by https://github.com/jpirko/lnst/commit/61a52a09025a615cc21883b720f3d0a087243887
