### ISSUE TITLE
race condition in create_if_pair

### ISSUE THREAD

**Issue by jtluka** [jpirko/lnst#182]
I hit occasional bug when working with net namespaces. So far I hit it only on RHEL6 and baremetal machine. I did not try to reproduce on virtual machines.

The xml part,
```xml
<lnstrecipe>
    <network>
        <host id="machine1">
            <interfaces>
                <eth id="out_if" label="localnet">
                    <!--addresses>
                        <address>2002::1/64</address>
                    </addresses-->
                </eth>
                <veth_pair>
                    <veth id="testifc1" netns="xyz" >
                        <addresses>
                            <address>2002::3/64</address>
                            <address>3003::1/64</address>
                        </addresses>
                    </veth>
                    <veth id="testifc2" />
                </veth_pair>
                <bridge id="br">
                    <slaves>
                        <slave id="out_if" />
                        <slave id="testifc2" />
                    </slaves>
                    <addresses>
                        <address>2002::10/64</address>
                    </addresses>
                </bridge>

            </interfaces>
        </host>
        <host id="machine2">
            <interfaces>
                <eth id="testiface" label="localnet">
                    <addresses>
                        <address>2002::2/64</address>
                        <address>4004::1/64</address>
                    </addresses>
                </eth>
            </interfaces>
        </host>

    </network>
    <task>
        <run command="echo" host="machine1" />
    </task>
</lnstrecipe>
```

It needs several runs to get following traceback:
```
2017-01-20 10:41:52        (machine2)        -   DEBUG: Executing: "ip link set eth1 down"
2017-01-20 10:41:52        (machine2)        -   DEBUG: Executing: "ip link set eth7 down"
2017-01-20 10:41:52        (machine1)        -   DEBUG: Creating network namespace xyz.
2017-01-20 10:41:52       (localhost)        -    INFO: Configuring interface out_if on machine machine1
2017-01-20 10:41:52        (machine1)        -   DEBUG: Executing: "ip addr flush eth2"
2017-01-20 10:41:52        (machine1)        -   DEBUG: Executing: "ethtool -A eth2 rx off tx off"
2017-01-20 10:41:52       (localhost)        -    INFO: Configuring interface testifc1 on machine machine1
2017-01-20 10:41:52        (machine1)        -   DEBUG: Executing: "ip link add veth0 type veth peer name veth1"
2017-01-20 10:41:52        (machine1)        -   DEBUG: Executing: "ethtool -i veth1"
2017-01-20 10:41:52        (machine1)        -   DEBUG: Executing: "ethtool -i veth0"
2017-01-20 10:41:52        (machine1)        -   DEBUG: Executing: "ip link set veth0 netns 10172"
2017-01-20 10:41:52        (machine1)      xyz   DEBUG: Created network namespace xyz
2017-01-20 10:41:52        (machine1)      xyz   DEBUG: Executing: "ethtool -i veth0"
2017-01-20 10:41:52        (machine1)        -   DEBUG: 
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/lnst/Slave/NetTestSlave.py", line 1182, in _process_msg
        result = method(*msg["args"])
      File "/usr/lib/python2.6/site-packages/lnst/Slave/NetTestSlave.py", line 330, in create_if_pair
        raise Exception("Configuration failed.")
    Exception: Configuration failed.
    
2017-01-20 10:41:52       (localhost)        -   ERROR: Exception raised during configuration.
```

I printed out the result returned by wait_for_result() on lnst-slave and noticed that it's something unexpected:
```
{'type': 'result', 'result': [{'hwaddr': '46:82:AB:BF:76:40', 'name': 'veth0'}]}
```

The result['result'] should be True returned by configure_interface() and not hwaddr. I think this comes from another command on the slave.

**Comment by jtluka** [comment]
Looks like that data come from SlaveMethods::map_if_by_hwaddr() called by SlaveMethods::set_if_netns()

**Comment by jtluka** [comment]
So I added a print of msgs for every wait_for_result() call. Below is failing and passing run:

Failing:
```
2017-01-20 11:33:58       (localhost)        -   DEBUG: Executing: "ip link set veth0 netns 11764"
>>>>>>>>>>>> wait_for_result() <<<<<<<<
[(None,
  {'record': {'args': None,
              'created': 1484908437.8277061,
              'exc_info': None,
              'exc_text': None,
              'filename': 'NetTestSlave.py',
              'funcName': 'add_namespace',
              'levelname': 'DEBUG',
              'levelno': 10,
              'lineno': 723,
              'module': 'NetTestSlave',
              'msecs': 827.70609855651855,
              'msg': 'Created network namespace xyz',
              'name': 'root',
              'origin_name': 'xyz',
              'pathname': '/usr/lib/python2.6/site-packages/lnst/Slave/NetTestSlave.py',
              'process': 11764,
              'processName': 'MainProcess',
              'relativeCreated': 104952.52108573914,
              'thread': 140481347200768,
              'threadName': 'MainThread'},
   'type': 'log'}),
 (None,
  {'data': {'result': True, 'type': 'result'},
   'netns': 'xyz',
   'type': 'from_netns'}),
 (None,
  {'record': {'args': None,
              'created': 1484908438.087709,
              'exc_info': None,
              'exc_text': None,
              'filename': 'ExecCmd.py',
              'funcName': 'exec_cmd',
              'levelname': 'DEBUG',
              'levelno': 10,
              'lineno': 56,
              'module': 'ExecCmd',
              'msecs': 87.708950042724609,
              'msg': 'Executing: "ethtool -i veth0"',
              'name': 'root',
              'origin_name': 'xyz',
              'pathname': '/usr/lib/python2.6/site-packages/lnst/Common/ExecCmd.py',
              'process': 11764,
              'processName': 'MainProcess',
              'relativeCreated': 105212.52393722534,
              'thread': 140481347200768,
              'threadName': 'MainThread'},
   'type': 'log'})]
2017-01-20 11:33:57       (localhost)      xyz   DEBUG: Created network namespace xyz
2017-01-20 11:33:58       (localhost)      xyz   DEBUG: Executing: "ethtool -i veth0"
>>>>>>>>>>>> wait_for_result() <<<<<<<<
[(None,
  {'data': {'if_data': {'devlink': None,
                        'driver': 'veth',
                        'hwaddr': 'E6:AF:67:6E:B3:F4',
                        'if_index': 51,
                        'ifi_type': 1,
                        'ip_addrs': [],
                        'master': {'other': [], 'primary': None},
                        'mtu': 1500,
                        'name': 'veth0',
                        'netns': None,
                        'peer': None,
                        'slaves': [],
                        'state': 'DOWN'},
            'type': 'if_update'},
   'netns': 'xyz',
   'type': 'from_netns'}),
 (None,
  {'record': {'args': None,
              'created': 1484908438.0960979,
              'exc_info': None,
              'exc_text': None,
              'filename': 'nlsocket.py',
              'funcName': 'post_init',
              'levelname': 'WARNING',
              'levelno': 30,
              'lineno': 878,
              'module': 'nlsocket',
              'msecs': 96.097946166992188,
              'msg': 'patching socket.recv_into()',
              'name': 'pyroute2.netlink.nlsocket',
              'origin_name': 'xyz',
              'pathname': '/usr/lib/python2.6/site-packages/pyroute2/netlink/nlsocket.py',
              'process': 11764,
              'processName': 'MainProcess',
              'relativeCreated': 105220.91293334961,
              'thread': 140481347200768,
              'threadName': 'MainThread'},
   'type': 'log'}),
 (None,
  {'record': {'args': None,
              'created': 1484908438.0966849,
              'exc_info': None,
              'exc_text': None,
              'filename': 'nlsocket.py',
              'funcName': 'post_init',
              'levelname': 'WARNING',
              'levelno': 30,
              'lineno': 878,
              'module': 'nlsocket',
              'msecs': 96.684932708740234,
              'msg': 'patching socket.recv_into()',
              'name': 'pyroute2.netlink.nlsocket',
              'origin_name': 'xyz',
              'pathname': '/usr/lib/python2.6/site-packages/pyroute2/netlink/nlsocket.py',
              'process': 11764,
              'processName': 'MainProcess',
              'relativeCreated': 105221.49991989136,
              'thread': 140481347200768,
              'threadName': 'MainThread'},
   'type': 'log'}),
 (None,
  {'data': {'result': [{'hwaddr': 'E6:AF:67:6E:B3:F4', 'name': 'veth0'}],
            'type': 'result'},
   'netns': 'xyz',
   'type': 'from_netns'})]
2017-01-20 11:33:58       (localhost)      xyz WARNING: patching socket.recv_into()
2017-01-20 11:33:58       (localhost)      xyz WARNING: patching socket.recv_into()
2017-01-20 11:33:58       (localhost)        -   DEBUG: 
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/lnst/Slave/NetTestSlave.py", line 1182, in _process_msg
        result = method(*msg["args"])
      File "/usr/lib/python2.6/site-packages/lnst/Slave/NetTestSlave.py", line 327, in create_if_pair
        raise Exception("Configuration failed.")
    Exception: Configuration failed.
```

Passing,
```
2017-01-20 11:34:03       (localhost)        -   DEBUG: Executing: "ip link set veth0 netns 11935"
>>>>>>>>>>>> wait_for_result() <<<<<<<<
[(None,
  {'record': {'args': None,
              'created': 1484908442.962826,
              'exc_info': None,
              'exc_text': None,
              'filename': 'NetTestSlave.py',
              'funcName': 'add_namespace',
              'levelname': 'DEBUG',
              'levelno': 10,
              'lineno': 723,
              'module': 'NetTestSlave',
              'msecs': 962.82601356506348,
              'msg': 'Created network namespace xyz',
              'name': 'root',
              'origin_name': 'xyz',
              'pathname': '/usr/lib/python2.6/site-packages/lnst/Slave/NetTestSlave.py',
              'process': 11935,
              'processName': 'MainProcess',
              'relativeCreated': 110087.64100074768,
              'thread': 140481347200768,
              'threadName': 'MainThread'},
   'type': 'log'}),
 (None,
  {'data': {'result': True, 'type': 'result'},
   'netns': 'xyz',
   'type': 'from_netns'}),
 (None,
  {'record': {'args': None,
              'created': 1484908443.2210269,
              'exc_info': None,
              'exc_text': None,
              'filename': 'ExecCmd.py',
              'funcName': 'exec_cmd',
              'levelname': 'DEBUG',
              'levelno': 10,
              'lineno': 56,
              'module': 'ExecCmd',
              'msecs': 221.02689743041992,
              'msg': 'Executing: "ethtool -i veth0"',
              'name': 'root',
              'origin_name': 'xyz',
              'pathname': '/usr/lib/python2.6/site-packages/lnst/Common/ExecCmd.py',
              'process': 11935,
              'processName': 'MainProcess',
              'relativeCreated': 110345.84188461304,
              'thread': 140481347200768,
              'threadName': 'MainThread'},
   'type': 'log'})]
2017-01-20 11:34:02       (localhost)      xyz   DEBUG: Created network namespace xyz
2017-01-20 11:34:03       (localhost)      xyz   DEBUG: Executing: "ethtool -i veth0"
>>>>>>>>>>>> wait_for_result() <<<<<<<<
[(None,
  {'data': {'if_data': {'devlink': None,
                        'driver': 'veth',
                        'hwaddr': 'BA:34:94:31:0A:1C',
                        'if_index': 54,
                        'ifi_type': 1,
                        'ip_addrs': [],
                        'master': {'other': [], 'primary': None},
                        'mtu': 1500,
                        'name': 'veth0',
                        'netns': None,
                        'peer': None,
                        'slaves': [],
                        'state': 'DOWN'},
            'type': 'if_update'},
   'netns': 'xyz',
   'type': 'from_netns'}),
 (None,
  {'record': {'args': None,
              'created': 1484908443.2290289,
              'exc_info': None,
              'exc_text': None,
              'filename': 'nlsocket.py',
              'funcName': 'post_init',
              'levelname': 'WARNING',
              'levelno': 30,
              'lineno': 878,
              'module': 'nlsocket',
              'msecs': 229.02894020080566,
              'msg': 'patching socket.recv_into()',
              'name': 'pyroute2.netlink.nlsocket',
              'origin_name': 'xyz',
              'pathname': '/usr/lib/python2.6/site-packages/pyroute2/netlink/nlsocket.py',
              'process': 11935,
              'processName': 'MainProcess',
              'relativeCreated': 110353.84392738342,
              'thread': 140481347200768,
              'threadName': 'MainThread'},
   'type': 'log'}),
 (None,
  {'record': {'args': None,
              'created': 1484908443.2296,
              'exc_info': None,
              'exc_text': None,
              'filename': 'nlsocket.py',
              'funcName': 'post_init',
              'levelname': 'WARNING',
              'levelno': 30,
              'lineno': 878,
              'module': 'nlsocket',
              'msecs': 229.59995269775391,
              'msg': 'patching socket.recv_into()',
              'name': 'pyroute2.netlink.nlsocket',
              'origin_name': 'xyz',
              'pathname': '/usr/lib/python2.6/site-packages/pyroute2/netlink/nlsocket.py',
              'process': 11935,
              'processName': 'MainProcess',
              'relativeCreated': 110354.41493988037,
              'thread': 140481347200768,
              'threadName': 'MainThread'},
   'type': 'log'}),
 (None,
  {'data': {'result': [{'hwaddr': 'BA:34:94:31:0A:1C', 'name': 'veth0'}],
            'type': 'result'},
   'netns': 'xyz',
   'type': 'from_netns'}),
 (None,
  {'data': {'result': True, 'type': 'result'},
   'netns': 'xyz',
   'type': 'from_netns'})]
```

I suspect that the message queue is not processed properly and previous results
are not cleared from the queue.

**Comment by olichtne** [comment]
Thanks for the debugging info, I believe I may have found a problem related to this, I've posted a [patch](https://lists.fedorahosted.org/archives/list/lnst-developers@lists.fedorahosted.org/message/KEEI6OX3ISMQ6PPO7UIGPP52IM7HUPF2/). Please try it out before applying, I don't know if I reproduced the issue correctly (and even then it was reproduced unreliably)...

**Comment by jtluka** [comment]
I hit another issue. It's probably related. NOTE that this is on the same version WITHOUT the fix. I'll check the patched version and report back.

```
    Traceback (most recent call last):
      File "/usr/bin/lnst-ctl", line 182, in get_recipe_result
        res = exec_action(action, nettestctl)
      File "/usr/bin/lnst-ctl", line 137, in exec_action
        return nettestctl.run_recipe()
      File "/usr/lib/python2.6/site-packages/lnst/Controller/NetTestController.py", line 648, in run_recipe
        self._prepare_network()
      File "/usr/lib/python2.6/site-packages/lnst/Controller/NetTestController.py", line 218, in _prepare_network
        iface.configure()
      File "/usr/lib/python2.6/site-packages/lnst/Controller/Machine.py", line 908, in configure
        self.update_from_slave()
      File "/usr/lib/python2.6/site-packages/lnst/Controller/Machine.py", line 816, in update_from_slave
        self.update(if_data)
      File "/usr/lib/python2.6/site-packages/lnst/Controller/Machine.py", line 820, in update
        self.set_hwaddr(if_data["hwaddr"])
    TypeError: 'bool' object is unsubscriptable
```

if_data is different data type than expected.

This issue happened with basically the same recipe, running twice. First run fails with original issue and second one fails with this exception.

**Comment by jtluka** [comment]
The patch solved the issue for me.
