### ISSUE TITLE
veth pairs cause infinite recursion on stack deconfiguration

### ISSUE THREAD

**Issue by jtluka** [jpirko/lnst#187]
This can be easily triggered by configuring veth pair with both veths under root namespace.
These devices will store reference to each other and store the peer interface id in Device._master["other"]. On deconfiguration of veth pair LNST will try to deconfigure first veth but since it has second veth in master["other"] it will start deconfiguring the second interface. The second interface has the first interface id in it's master["other"] so it will attempt to deconfgure the first veth device, and so on until max level of recursion is reached.

Reproducer:
```xml
<lnstrecipe>
    <network>
        <host id="tm1">
            <interfaces>
                <eth id="nic1" label="testnet"/>
                <veth_pair>
                    <veth id="veth1"/>
                    <veth id="veth2"/>
                </veth_pair>
            </interfaces>
        </host>
    </network>

    <task>
        <run host="tm1" command="sleep 1"/>
    </task>
</lnstrecipe>
```

lnst-ctl -d config_only recipe.xml; lnst-ctl deconfigure
```
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/lnst/Slave/NetTestSlave.py", line 1182, in _process_msg
        result = method(*msg["args"])
      File "/usr/lib/python2.7/site-packages/lnst/Slave/NetTestSlave.py", line 542, in machine_cleanup
        self._if_manager.deconfigure_all()
      File "/usr/lib/python2.7/site-packages/lnst/Slave/InterfaceManager.py", line 242, in deconfigure_all
        dev.clear_configuration()
      File "/usr/lib/python2.7/site-packages/lnst/Slave/InterfaceManager.py", line 567, in clear_configuration
        m_dev.clear_configuration()
      File "/usr/lib/python2.7/site-packages/lnst/Slave/InterfaceManager.py", line 567, in clear_configuration
        m_dev.clear_configuration()
      File "/usr/lib/python2.7/site-packages/lnst/Slave/InterfaceManager.py", line 567, in clear_configuration
        m_dev.clear_configuration()
      File "/usr/lib/python2.7/site-packages/lnst/Slave/InterfaceManager.py", line 567, in clear_configuration
        m_dev.clear_configuration()
```

**Comment by jtluka** [comment]
Patches posted:
https://lists.fedorahosted.org/archives/list/lnst-developers@lists.fedorahosted.org/thread/PWE3FL3PTONBIQHSX7U3F2HCH6HBLQY4/
https://lists.fedorahosted.org/archives/list/lnst-developers@lists.fedorahosted.org/thread/XP44LIAINRIWBD2VJFJ3KPD2JYDVEHEY/
