### ISSUE TITLE
no html output possible on rhel6

### ISSUE THREAD

**Issue by jtluka** [jpirko/lnst#89]
Seems that html output generation is not working for rhel6 release.

It contains buggy [1] lxml (version 2.2.3) that's causing following issue
when running from python script,

```
Traceback (most recent call last):
  File "/usr/bin/lnst-ctl", line 332, in <module>
    sys.exit(main())
  File "/usr/bin/lnst-ctl", line 326, in main
    handle.write(res_serializer.get_result_html())
  File
"/usr/lib/python2.6/site-packages/lnst/Controller/NetTestResultSerializer.py",
line 287, in get_result_html
    xslt = etree.parse(xslt_url)
  File "lxml.etree.pyx", line 2692, in lxml.etree.parse
(src/lxml/lxml.etree.c:49594)
  File "parser.pxi", line 1500, in lxml.etree._parseDocument
(src/lxml/lxml.etree.c:71364)
  File "parser.pxi", line 1529, in lxml.etree._parseDocumentFromURL
(src/lxml/lxml.etree.c:71647)
  File "parser.pxi", line 1429, in lxml.etree._parseDocFromFile
(src/lxml/lxml.etree.c:70742)
  File "parser.pxi", line 975, in
lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:67740)
  File "parser.pxi", line 539, in
lxml.etree._ParserContext._handleParseResultDoc
(src/lxml/lxml.etree.c:63824)
  File "parser.pxi", line 625, in lxml.etree._handleParseResult
(src/lxml/lxml.etree.c:64745)
  File "parser.pxi", line 565, in lxml.etree._raiseParseError
(src/lxml/lxml.etree.c:64088)
lxml.etree.XMLSyntaxError: Attempt to load network entity
http://www.lnst-project.org/files/result_xslt/xml_to_html.xsl
```
The fix seems to be not to use etree.parse directly on url but rather 
use urllib or similar to download the data [1] and pass them to lxml.

Thoughts on this?

[1] https://bugs.launchpad.net/lxml/+bug/673205
[2] http://stackoverflow.com/questions/6199666/lxml-only-loading-a-single-network-entity-before-raising-xmlsyntaxerror

**Comment by jtluka** [comment]
Fixed by 1dc6f97f18f1ef9250906f66b086bc9eadec2f8b
